### Numpy stands for "Numerical Python" for use data analysis/Science,and cloud computing,ML.
### !pip install numPy.(Installtion process)
### Array make with 1D, 2D, 3D....ndarray.We store data in an Array. 
### Suppose i make a list [1,2,3,4,5] = 1=100, 101,102 Location. This is a series of data
### we make strutured array. from an unstructed data.
### All elements of an array are same data type. but if need diffrenet use List.
### Array are static and can't be changed. but if you need dynamic use List.
### NumPy array use less space. Vs of List.

<a id="1"></a>
<h2 style="color:#ff0000;font-size:30px;font-family:initial;text-align:center;"><strong>1.<strong style="color:#005aac;font-size:30px;font-family:initial;"><b>Create 1D Array</b><strong style="color:#ff0000;font-size:30px;font-family:initial;">:-</strong></strong></strong></h2>

In [5]:
#how to create NumPy Arrays?

import numpy as np #alias dummy name
list1 = [10,20,30,40,50]
array1 = np.array(list1) #np is same as use use dummy name #If we want to convert the datatype then we'll use dtype='float','U32'.
print (array1, type(array1))#It is a 1D array. Type of array1 it shows 
print(array1.shape) #it is shwoing rows and columns
print(array1.ndim) #It shwoing the dimension of array

[10 20 30 40 50] <class 'numpy.ndarray'>
[10 20 30 40 50]
(5,)
1


In [6]:
#Now suppose we want to change the type of whole array.
#how to create NumPy Arrays?

import numpy as np #alias dummy name
list1 = [10,20,30,40,50]
array1 = np.array(list1,dtype=float) #np is same as use use dummy name #If we want to convert the datatype then we'll use dtype='float','U32'.
print (array1, type(array1))#It is a 1D array. Type of array1 it shows 
print(array1.shape)
print(array1.ndim)

[10. 20. 30. 40. 50.] <class 'numpy.ndarray'>
(5,)
1


In [7]:
#Now You want to change the type CHAR
#we also can mention what we need #(How to change datatype as per your need)

import numpy as np #alias dummy name
list1 = [10,20,30,40,50]
array1 = np.array(list1,dtype='U32') #np is same as use use dummy name #for charecter use U32
print(array1)


['10' '20' '30' '40' '50']


In [55]:
type(array1) #N= infinity array

numpy.ndarray

In [10]:
data1 = [1, 2, 3, 4, 5] # list
arr1 = np.array(data1)
print (data1, type(data1))
print (arr1, type(arr1))

[1, 2, 3, 4, 5] <class 'list'>
[1 2 3 4 5] <class 'numpy.ndarray'>


In [3]:
#how to create NumPy Arrays?

import numpy as np #alias dummy name
list1 = [10,20.88,30,40,50]
array1 = np.array(list1) #np is same as use use dummy name
print(array1)
#all are in float value. so remember list is same but type must be different.

[10.   20.88 30.   40.   50.  ]


In [4]:
#how to create NumPy Arrays?

import numpy as np #alias dummy name
list1 = [10,"hello",30,40,50]
array1 = np.array(list1) #np is same as use use dummy name
print(array1)


['10' 'hello' '30' '40' '50']


In [11]:
#write array using range(This is a shortcart method)
import numpy as np
array1= np.arange(1,8) #1 is starting value and 7 is ending value 
print(array1)

[1 2 3 4 5 6 7]


In [10]:
#write array using range(This is a shortcart method)
import numpy as np #Now make 2d array
array1= np.arange(12,18).reshape((2,3)) #1 is starting value and 7 is ending value 
print(array1) #No of rows: 2 no of columns: 3 total elements: 6... 2x3 matrix

[[12 13 14]
 [15 16 17]]


In [11]:
#write array using range(This is a shortcart method)
import numpy as np #Now make 2d array
array1= np.arange(12,18).reshape((3,2)) #1 is starting value and 7 is ending value 
print(array1) #No of rows: 3 no of columns: 2 total elements: 6... 3x2 matrix

[[12 13]
 [14 15]
 [16 17]]


In [13]:
# Finding the max, min, sum of the array
array1 = np.array([1,2,3,10,15,4])
print("The array:",array1)
print("The maximum element:",array1.max())
print("The minimum element:",array1.min())
print("The sum of the elements:",array1.sum())

The array: [ 1  2  3 10 15  4]
The maximum element: 15
The minimum element: 1
The sum of the elements: 35


In [16]:
# Find the square-root and standard deviation of the array
array1 = np.array([[1,2,30],[10,15,4]]) #Let's take a 2d array
print(np.sqrt(array1))
print(np.std(array1))



[[1.         1.41421356 5.47722558]
 [3.16227766 3.87298335 2.        ]]
10.044346115546242


In [12]:
array1 = np.zeros(4)
print(array1) #1d array

[0. 0. 0. 0.]


In [13]:
array1 = np.zeros((4,2))
print(array1) #2d array #2 Brackets

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


<a id="1"></a>
<h2 style="color:#ff0000;font-size:30px;font-family:initial;text-align:center;"><strong>2.<strong style="color:#005aac;font-size:30px;font-family:initial;"><b>Create 2D Array</b><strong style="color:#ff0000;font-size:30px;font-family:initial;">:-</strong></strong></strong></h2>

In [12]:
# Now we create 2d array
import numpy as np
list1 = [[10,20,30], [40,50,60]] #2 brackets here so we consider it is 2D ARRAY
array1 = np.array(list1)
print(array1)

[[10 20 30]
 [40 50 60]]


In [21]:
# Multiply 2 array each element with specific index
a = np.array([10,20,30])
b = np.array([40,50,60]) # It should be same order
c= a*b
print(c)


[ 400 1000 1800]


In [23]:
a = np.array([10,20,30])
b = np.array([40,50,60])
print("\nAdding arrays a and b ..")
c = a + b;
print(c)


Adding arrays a and b ..
[50 70 90]


In [9]:
#How to create zeros
import numpy as np
array1 = np.zeros((4,2)) #No of rows 4 and no of colmuns 2
print(array1)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [8]:
#write 2d.3d array by using arange
import numpy as np
array1 = np.arange(11,17).reshape((2,3))
print(array1)

[[11 12 13]
 [14 15 16]]


In [10]:
#How to create once
import numpy as np
array1 = np.ones((4,2)) #No of rows 4 and no of colmuns 2
print(array1)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


Varies Attributes of NumPy array:
1.) ndim #dimention of array
2.) shape #no of rows and columns
3.) size
4.) dtype #data type
5.) itemsize #no of bytes used in memory


In [24]:
import numpy as np
array1 = [10,20,30,40,50]
array1 = np.array(array1)
array1.ndim     #1D ARRAY

1

In [26]:
array1 = [[10,20,30], [40,50,60], [70,80,90]]
array1 = np.array(array1)
array1.ndim #2D ARRAY

2

In [15]:
array1 = [[[10,20,30], [40,50,60], [70,80,90], [90,100,110]]]
array1 = np.array(array1)
array1.ndim #3D ARRAY

3

In [25]:
import numpy as np
array1 = [10,20,30,40,50]
array1 = np.array(array1)
array1.shape    #No of elements for 1d that why 5,

(5,)

In [21]:
array1 = [[10,20,30], [40,50,60], [70,80,90]]
array1 = np.array(array1)
array1.shape #for 2d array

(3, 3)

In [22]:
array1 = [[[10,20,30], [40,50,60], [70,80,90], [90,100,110]]]
array1 = np.array(array1)
array1.shape #3D ARRAY

(1, 4, 3)

In [14]:
import numpy as np
array1 = [10,20,30,40,50]
array1 = np.array(array1)
array1.size

5

In [33]:
array1 = [[10,20,30], [40,50,60], [70,80,90]]
array1 = np.array(array1)
array1.size #2D ARRAY

9

In [35]:
array1 = [[[10,20,30], [40,50,60], [70,80,90], [90,100,110]]]
array1 = np.array(array1)
array1.size #3D ARRAY

12

In [26]:
import numpy as np
array1 = [10,20,30,40,50]
array1 = np.array(list1)
array1.dtype

dtype('int32')

In [28]:
import numpy as np
array1 = [10,20,30.67,40,50]
array1 = np.array(array1)
array1.dtype

dtype('float64')

<a id="1"></a>
<h2 style="color:#ff0000;font-size:30px;font-family:initial;text-align:center;"><strong>3.<strong style="color:#005aac;font-size:30px;font-family:initial;"><b>Create 3D array</b><strong style="color:#ff0000;font-size:30px;font-family:initial;">:-</strong></strong></strong></h2>

In [36]:
arr = np.array([[[10,20],[30,40]],
 [[50,60],[70,80]] ])
print(arr)
print(arr.ndim)

[[[10 20]
  [30 40]]

 [[50 60]
  [70 80]]]
3


In [38]:
arr = np.array([[[[[[[10,20],[30,40]],
 [[50,60],[70,80]]]]]]])
print(arr)
print(arr.ndim) #7D ARRAY

[[[[[[[10 20]
      [30 40]]

     [[50 60]
      [70 80]]]]]]]
7


In [39]:
# Bitwise And and OR Operation
a = 10
b = 12
print("binary representation of a:",bin(a))
print("binary representation of b:",bin(b))
print("Bitwise-and of a and b: ",np.bitwise_and(a,b))
print("Bitwise-or of a and b: ",np.bitwise_or(a,b))

binary representation of a: 0b1010
binary representation of b: 0b1100
Bitwise-and of a and b:  8
Bitwise-or of a and b:  14


# Indexing in numpy Array

10,20,30,40,50,60
 0  1  2  3  4  5(Index No)

In [23]:
#We are use indexing for fetch a particular output(accaess array element)
import numpy as np
array1 = np.array([10,20,30,40,50,60])
print(array1[0])

10


In [30]:
print(array1[-1])

60


   0   1   2
0- 10   20  30

1- 40  50   60

2- 70 80 90
Row:column

In [31]:
import numpy as np
array1 = np.array([[10,20,30], [40,50,60], [70,80,90]])
print(array1[1,2])

60


In [32]:
print(array1[0,:])

[10 20 30]


In [33]:
print(array1[:,1])

[20 50 80]


# Slicing in numpy arrays.

# slicing is the way to extract a subset of data from a numpy array.
# ([10,20,30,40,50,60,70])
#    0   1   2   3    4   5   6
#   -7   -6  -5  -4  -3  -2  -1

In [44]:
#1D Array
#[start:end],[start:end:step]
import numpy as np
array1 = np.array([10,20,30,40,50,60,70])
print(array1[1:3]) #Start bit and stop bit

[20 30]


In [45]:
print(array1[1:6:2]) #Start bit #step bit #and stop bit

[20 40 60]


In [46]:
print(array1[-1:])

[70]


In [53]:
print(array1[-1:-3:-1]) #-1 is direction

[70 60]


In [39]:
print(array1[::2])

[10 30 50 70]


In [41]:
[print(array1[::-1])]

[70 60 50 40 30 20 10]


[None]

In [55]:
#2D Array
import numpy as np
array1 = np.array([[15,16,17], [25,26,27], [35,36,37], [45,46,47]])
print(array1[1, ])

[25 26 27]


   0  1  2
0  15 16 17
1  25 26 27
2  35 36 37
3  45 46 47

= 4*3
Row = 4 and colmun = 3

In [56]:
print(array1[:,1])

[16 26 36 46]


In [4]:
print(array1[1:3 , 1:3]) #Start with Row 1 & 2 #and for column 1&2

[[26 27]
 [36 37]]


In [5]:
print(array1[1:3, 1])

[26 36]


In [6]:
print(array1[1:3, :1])

[[25]
 [35]]


In [7]:
print(array1[1:3 , 1:])

[[26 27]
 [36 37]]


In [83]:
a = np.array([[10, 20, 30, 40, 50],
 [60, 70, 80, 90, 100],
 [110, 120, 130, 140, 150],
 [160, 170, 180, 190, 200],
 [210, 220, 230, 240, 250]])
print("The Diagonal elements of the matrix",a.diagonal())
# Eigen Values and Eigen Vectors
vals, vecs = np.linalg.eig(a)
print("Eigenvalues:", vals)
print("Eigenvectors:", vecs)



The Diagonal elements of the matrix [ 10  70 130 190 250]
Eigenvalues: [ 6.86420807e+02 -3.64208074e+01  4.42948146e-14 -3.61711347e-15
 -4.89293952e-15]
Eigenvectors: [[-0.10797496  0.67495283  0.39507493 -0.21036038  0.19806751]
 [-0.25277499  0.3603897  -0.65303237  0.05245984 -0.07950282]
 [-0.39757502  0.04582657  0.40069653  0.68228909 -0.63462597]
 [-0.54237506 -0.26873656 -0.42259568 -0.68051616  0.71549038]
 [-0.68717509 -0.58329969  0.27985658  0.15612762 -0.19942909]]


In [58]:
# Original Matrix
print(a)
print()
# Transpose Matrix
arr1 = a.T
#arr1 = a.transpose()
print(arr1)

[[ 10  20  30  40  50]
 [ 60  70  80  90 100]
 [110 120 130 140 150]
 [160 170 180 190 200]
 [210 220 230 240 250]]

[[ 10  60 110 160 210]
 [ 20  70 120 170 220]
 [ 30  80 130 180 230]
 [ 40  90 140 190 240]
 [ 50 100 150 200 250]]


In [59]:
# Tile for repeating numbers
original_array = np.array([1, 2, 3])
print("Original array:")
print(original_array)
tiled_array = np.tile(original_array,(4,3))
print("\nTiled array:")
print(tiled_array)


Original array:
[1 2 3]

Tiled array:
[[1 2 3 1 2 3 1 2 3]
 [1 2 3 1 2 3 1 2 3]
 [1 2 3 1 2 3 1 2 3]
 [1 2 3 1 2 3 1 2 3]]


In [60]:
# Array for specified Numbers
a = np.full([4,4],26)
print(a)


[[26 26 26 26]
 [26 26 26 26]
 [26 26 26 26]
 [26 26 26 26]]


In [62]:
# np.add.accumulate() performs an element-wise addition and returns the accumulated sums.
arr = np.array([10, 20, 30, 40, 50])
print(arr)
# Use np.add.accumulate() to compute the accumulated sums
accumulate_result = np.add.accumulate(arr)
print("Result of np.add.accumulate():")
print(accumulate_result)


cumsum_result = np.cumsum(arr)
print("Result of np.cumsum():")
print(cumsum_result)


[10 20 30 40 50]
Result of np.add.accumulate():
[ 10  30  60 100 150]
Result of np.cumsum():
[ 10  30  60 100 150]


# What is linalg?
## Ans: np.linalg is used to compute the inverse of a matrix A. linalg stands for "linear algebra", and it's a module in NumPy that provides functions for linear algebra operations, such as matrix inversion, determinant calculation, eigenvalue decomposition, and more.
### The linalg module is used for several reasons: 1. Matrix or any algebric oparation. 2.Determine Accuracy of a data.

In [65]:
# Create a 3x3 matrix
A = np.array([[1, 2, 3],
 [0, 1, 4],
 [5, 6, 0]])
print("Original matrix A:")
print(A)
# Compute the inverse of the matrix
A_inv = np.linalg.inv(A)   #In the code, np.linalg is used to compute the inverse of a matrix A. linalg stands for "linear algebra", and it's a module in NumPy that provides functions for linear algebra operations, such as matrix inversion, determinant calculation, eigenvalue decomposition, and more.
print("\nInverse of matrix A:")
print(A_inv)
# Verify the result by multiplying A and its inverse
identity_matrix = np.dot(A, A_inv)
print("\nIdentity matrix (A * A_inv):")
print(identity_matrix)

Original matrix A:
[[1 2 3]
 [0 1 4]
 [5 6 0]]

Inverse of matrix A:
[[-24.  18.   5.]
 [ 20. -15.  -4.]
 [ -5.   4.   1.]]

Identity matrix (A * A_inv):
[[ 1.00000000e+00 -1.77635684e-15 -4.44089210e-16]
 [ 0.00000000e+00  1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00]]


Eigenvalues: [ 0.00000000e+00  1.04000000e+02 -2.06415243e-31 -2.18952885e-47]
Eigenvectors: [[-0.8660254  -0.5         0.73164306 -0.8660254 ]
 [ 0.28867513 -0.5        -0.68073689  0.28867513]
 [ 0.28867513 -0.5        -0.02545309  0.28867513]
 [ 0.28867513 -0.5        -0.02545309  0.28867513]]


# Arithmetic oparations on numpy arrays 

In [66]:
#the best way to save numeric oparations
#2d matrix
import numpy as np
x = np.array([[1,2],
             [3,4]])

y = np.array([[11,12],
             [13,14]])
z = x+y
print(z)

[[12 14]
 [16 18]]


In [10]:
#the best way to save numeric oparations
#2d matrix
import numpy as np
x = np.array([[1,2],
             [3,4]])

y = np.array([[11,12],
             [13,14]])
z = x-y
print(z)

[[-10 -10]
 [-10 -10]]


In [11]:
#the best way to save numeric oparations
#2d matrix
import numpy as np
x = np.array([[1,2],
             [3,4]])

y = np.array([[11,12],
             [13,14]])
z = x*y
print(z)

[[11 24]
 [39 56]]


In [12]:
#the best way to save numeric oparations
#2d matrix
import numpy as np
x = np.array([[1,2],
             [3,4]])

y = np.array([[11,12],
             [13,14]])
z = x@y                     #@Matrix maltiplication
print(z)

[[37 40]
 [85 92]]


What is Matrix Multiplication?
--> [[1,2]]  [[11,12]]
    [[3,4]]  [[13,14]]
    
    [[1x11 + 2x13 1x12 + 2x14]]
    [[3x11 + 4x13 3x12 + 4x14]]
    

In [67]:
#the best way to save numeric oparations
#2d matrix
import numpy as np
x = np.array([[1,2],
             [3,4]])

y = np.array([[11,12],
             [13,14]])
z = y / x
print(z)

[[11.          6.        ]
 [ 4.33333333  3.5       ]]


In [68]:
#the best way to save numeric oparations
#2d matrix(Floor division/Round figure)
import numpy as np
x = np.array([[1,2],
             [3,4]])

y = np.array([[11,12],
             [13,14]])
z = y//x
print(z)

[[11  6]
 [ 4  3]]


In [69]:
#the best way to save numeric oparations
#2d matrix(PowerX2)
import numpy as np
x = np.array([[1,2],
             [3,4]])

y = np.array([[11,12],
             [13,14]])
z = y ** x 
print(z)

[[   11   144]
 [ 2197 38416]]


In [17]:
#the best way to save numeric oparations
#2d matrix(Reminder)
import numpy as np
x = np.array([[1,2],
             [3,4]])

y = np.array([[11,12],
             [13,14]])
z = y % x
print(z)

[[0 0]
 [1 2]]


In [72]:
#the best way to save numeric oparations
#2d matrix(Transpose)
import numpy as np
x = np.array([[1,2],
             [3,4]])

y = np.array([[11,12],
             [13,14]])
print(x.transpose())
print(y.transpose())

[[1 3]
 [2 4]]
[[11 13]
 [12 14]]


In [84]:
import math
print(math.gcd(2,3))

1


In [88]:
# Finding the GCD using Numpy
print(np.gcd(12,21))

# Finding LCM
arr = np.array([3, 6, 9])
x = np.lcm.reduce(arr)
print(x)


3
18


In [94]:
names = np.array(['Ishika','Kuheli','Debosmita','Ranajit','Arkadeep','Harsh','Disha'])
print (names)
print (names[names == 'Ishika'])
print (names[names != 'Ishika'])
print (names[(names == 'Ishika') | (names == 'Kuheli')])
names[names != 'Debosmita'] = 'Harsh'
print (names)
print (np.unique(names))

['Ishika' 'Kuheli' 'Debosmita' 'Ranajit' 'Arkadeep' 'Harsh' 'Disha']
['Ishika']
['Kuheli' 'Debosmita' 'Ranajit' 'Arkadeep' 'Harsh' 'Disha']
['Ishika' 'Kuheli']
['Harsh' 'Harsh' 'Debosmita' 'Harsh' 'Harsh' 'Harsh' 'Harsh']
['Debosmita' 'Harsh']


# Sorting 2D Arrays Numpy
## 

In [73]:
import numpy as np
x = np.array([[12,11,15],
             [21,25,20],
             [18,27,16]])
y = np.sort(x)
print(y)

[[11 12 15]
 [20 21 25]
 [16 18 27]]


In [30]:
import numpy as np
x = np.array([[12,11,15],
             [21,25,20],
             [18,27,16]])
y = np.argsort(x, axis=1) #Row wise(Print Index value)
print(y)

[[1 0 2]
 [2 0 1]
 [2 0 1]]


In [75]:
import numpy as np
x = np.array([[12,11,15],
             [21,25,20],
             [18,27,16]])
x.sort() #Column wise
print(x)

[[11 12 15]
 [20 21 25]
 [16 18 27]]


In [76]:
import numpy as np
x = np.array([[12,11,15],
             [21,25,20],
             [18,27,16]])
y = np.argsort(x, axis=0) #Column wise
print(y)

[[0 0 0]
 [2 1 2]
 [1 2 1]]


# sorting 1D numpy array.

In [78]:
import numpy as np
x = np.array([199,788,55,67])
y = np.sort(x)
print(y)

[ 55  67 199 788]


In [79]:
import numpy as np
x = np.array([199,788,55,67])
y = np.sort(x)[::-1] #For reverse
print(y)

[788 199  67  55]


In [81]:
import numpy as np
x = np.array([199,788,55,67])
y = np.argsort(x)
print(x)#index no
print(y)

[199 788  55  67]
[2 3 0 1]


# statistic oparation on NumPy array.

In [2]:
import numpy as np
x = np.array([4,2,3,9,7])
y = np.max(x)
print(y)

9


In [3]:
import numpy as np
x = np.array([4,2,3,9,7])
y = np.mean(x)
print(y)

5.0


In [4]:
import numpy as np
x = np.array([4,2,3,9,7])
y = np.median(x)
print(y)

4.0


In [5]:
import numpy as np
x = np.array([4,2,3,9,7])
y = np.prod(x)
print(y)

1512


In [6]:
#Varios and standerd deviation
import numpy as np
x = np.array([4,2,3,9,7])
y = np.var(x)
print(y)

6.8


In [7]:
import numpy as np
x = np.array([4,2,3,9,7])
y = np.std(x)
print(y)

2.6076809620810595


# Broadcasting

## V = [1 2 3] (1x3)
## V1 = [1
           2
           3] (3x1)
           
### Must have same dimenstion if not then we use Broadcasting method
### Broadcasting হলো যখন NumPy অটোমেটিক্যালি ভিন্ন ডাইমেনশনের arrays নিয়ে অপারেশন (যেমন যোগ, বিয়োগ) করে।

(4,)


ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [25]:
a = np.array([[ 0, 0, 0],  #This is 2d array
         [10, 10, 10],
         [20, 20, 20],
         [30, 30, 30]])
print (a.shape)#So this is a 4x3 matrix
print(a.ndim)
b = np.array([0, 1, 2]) #and this is 3x0 matrix
print (b.shape)
print(b.ndim)

result = a + b #Use broadcast function
print(result) #so now a and b matrix add each other but noticed they are not in same dimension

a = np.array([[0], [10], [20], [30]]) #Now make a 2d array
print (a.ndim)#Check dimension
print(a.shape)
print()

result = a - b #Now we add 1d+2d array
print (result)




(4, 3)
2
(3,)
1
[[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]
2
(4, 1)

[[ 0 -1 -2]
 [10  9  8]
 [20 19 18]
 [30 29 28]]


# Searching method(For bank note authetication)

In [50]:
# creating the array
arr = np.array([100, 200, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 300, 300, 400, 610, 670, 410])
print(arr,type(arr))

# Searching for 500 in the array
i = np.where(arr == 500)
print("i = {}".format(i))


[100 200 500 500 500 500 500 500 500 500 500 500 500 500 500 500 500 500
 500 300 300 400 610 670 410] <class 'numpy.ndarray'>
i = (array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18],
      dtype=int64),)


# Minor Project(Python password genartor by NumPy)

In [5]:
import numpy as np
import string

def generate_password(length=12):
    # Define the pool of characters
    characters = list(string.ascii_letters + string.digits + string.punctuation)
    
    # Randomly select characters from the pool
    password = ''.join(np.random.choice(characters, size=length))
    
    return password

# Example usage
print(generate_password())

<Yg+IK|)cK{b


# Minor Project(Python emoji genarator by NumPy)

In [63]:
import numpy as np

def generate_emoji_sequence(length=20):
    # Define the pool of emojis
    emojis = [
        '😀', '😃', '😄', '😁', '😆', '😅', '😂', '🤣', '😊', '😇', '🙂', '🙃', '😉', '😌', '😍', '🥰', '😘', '😗',
        '😙', '😚', '😋', '😛', '😜', '🤪', '😝', '🤑', '🤗', '🤭', '🤫', '🤔', '🤐', '🤨', '😐', '😑', '😶', '😏',
        '😒', '🙄', '😬', '🤥', '😌', '😔', '😪', '🤤', '😴', '😷', '🤒', '🤕', '🤢', '🤮', '🤧', '🥵', '🥶', '🥴',
        '😵', '🤯', '🤠', '🥳', '😎', '🤓', '🧐', '😕', '😟', '🙁', '😮', '😯', '😲', '😳', '🥺', '😦', '😧', '😨',
        '😰', '😥', '😢', '😭', '😱', '😖', '😣', '😞', '😓', '😩', '😫', '🥱', '😤', '😡', '😠', '🤬', '😈', '👿',
        '💀', '☠️', '💩', '🤡', '👹', '👺', '👻', '👽', '👾', '🤖', '😺', '😸', '😹', '😻', '😼', '😽', '🙀', '😿',
        '😾'
    ]
    
    # Randomly select emojis from the pool
    emoji_sequence = ''.join(np.random.choice(emojis, size=length))
    
    return emoji_sequence

# Example usage
print(generate_emoji_sequence())


🤢🤪☠️😉😦👻😘😒😒🤓🤕😖😙🤪☠️😻😈😕😄😇


# Emoji selection by user


In [80]:
import numpy as np

def get_emoji(emotion):
    # Define a dictionary mapping words to lists of emojis
    emoji_dict = {
        'happy': ['😀', '😃', '😄', '😁', '😊'],
        'sad': ['😢', '😭', '😞', '😟', '😔'],
        'angry': ['😠', '😡', '🤬', '😤', '😒'],
        'love': ['😍', '😘', '🥰', '❤️', '💕'],
        'surprised': ['😲', '😮', '😯', '😳', '🤯'],
        'laughing': ['😂', '🤣', '😹', '😆', '😁'],
        'crying': ['😭', '😢', '😿', '😥', '😓'],
        'sleepy': ['😴', '😪', '😌', '😩', '🥱'],
        'confused': ['😕', '😟', '🙁', '😖', '😞'],
        'cool': ['😎', '😏', '🆒', '😎', '😜']
    }
    
    # Return a randomly selected emoji from the corresponding list
    return np.random.choice(emoji_dict.get(emotion.lower(), ['🤔']))

# Get user input for the emotion
emotion = input("Enter an emotion (e.g., happy, sad, angry): ")

# Get and print the corresponding emoji
print(get_emoji(emotion))


Enter an emotion (e.g., happy, sad, angry): angry
😒


# Minor Project (Txt to handwriting)

In [1]:
!pip install pywhatkit


In [2]:
import pywhatkit as pw
txt = '''Hi....My name is souvik saha.I live at Khardah. Pursuing B.TECH from TECHNO INDIA UNIVERSITY'''
pw.text_to_handwriting(txt, "AI_Assignment.png", [0,0,138])
print("End")



UnableToAccessApi: Unable to access Pywhatkit api right now

In [13]:
import phonenumbers

In [16]:
from phonenumbers import timezone,geocoder,carrier
number=input("Enter your no with +__:")
phone=phonenumbers.parse(number)
time=timezone.time_zones_for_number(phone)
car=carrier.name_for_number(phone, "en")
reg=geocoder.description_for_number(phone, "en")
print(phone)
print(time)
print(car)
print(reg)

Enter your no with +__:+919318473275
Country Code: 91 National Number: 9318473275
('Asia/Calcutta',)
Reliance Jio
India


Handwritten text saved to handwritten.png


OSError: cannot open resource